import { GROUND_RATIO } from './data.js';

export function createInitialState() {
  return {
    mode: 'title',
    paused: false,
    arenaMode: false,
    arenaActive: false,
    arenaSelectedMob: null,
    dialogueOpen: false,
    insideShop: false,
    shopType: null,
    levelComplete: false,
    tutorialComplete: false,
    tutorialStep: 0,
    currentLevel: 0,
    currentArea: 'grassy',
    input: { left: false, right: false, jump: false, guard: false },
    mouse: { x: 0, y: 0 },
    bowMode: false,
    bowTarget: null,
    cameraShake: 0,
    effects: [],
    hazards: [],
    drops: [],
    projectiles: [],
    enemies: [],
    npcs: [],
    companions: [],
    floatingPlatforms: [],
    envHazardTimer: 0,
    envHazardEnabled: false,
    envHazardInterval: 4,
    worldProgress: { grassy: 0, ice: 0, lava: 0, lightning: 0, void: 0 },
    activeQuest: null,
    questProgress: 0,
    questStartHp: 0,
    questDamageTaken: false,
    player: {
      x: 140,
      y: 0,
      w: 44,
      h: 62,
      vx: 0,
      vy: 0,
      speed: 230,
      facing: 1,
      grounded: false,
      hp: 20,
      maxHp: 20,
      baseMaxHp: 20,
      invuln: 0,
      attackTimer: 0,
      attackCooldown: 0,
      arrows: 10,
      money: 100,
      shieldUp: false,
      talkedToMaster: false,
      dummiesKilled: 0,
      totalMoved: 0,
      totalJumps: 0,
      totalSwings: 0,
      totalShots: 0,
      potionSlots: ['healing', null, null],
      maxPotionSlots: 3,
      potionEffects: {
        shield: { active: false, timer: 0, strength: 0 },
        damage: { active: false, timer: 0, mult: 1 },
        speed: { active: false, timer: 0, mult: 1 }
      },
      swordMaterial: 'wooden',
      swordLevel: 1,
      shieldMaterial: null,
      shieldLevel: 0,
      armorMaterial: null,
      armorLevel: 0,
      helmetMaterial: null,
      helmetLevel: 0,
      bowType: 'basic',
      arrowType: 'basic',
      hasJetpack: false,
      jetpackUpgraded: false,
      jetpackFuel: 7,
      maxJetpackFuel: 7,
      jetpackActive: false,
      healthUpgrades: 0,
      hasForceField: false,
      forceFieldLevel: 1,
      forceFieldHP: 5,
      forceFieldMaxHP: 5,
      forceFieldActive: false,
      forceFieldRespawn: 0,
      element: null,
      unlockedElements: [],
      elementCooldown: 0,
      elementCharging: false,
      elementUsed: false,
      elementWheelOpen: false,
      elementHoldStart: 0,
      graduationTalkDone: false,
      hasSwordOfLight: false,
      hasBowOfLight: false,
      hasBlessingOfLight: false,
      blessingAuraTimer: 0
    },
    tutorialSteps: [
      { text: 'USE A / D TO MOVE', check: (s) => s.player.totalMoved > 180 },
      { text: 'PRESS W OR SPACE TO JUMP', check: (s) => s.player.totalJumps >= 2 },
      { text: 'KILL SWORD DUMMIES (CLICK)', check: (s) => s.enemies.filter((e) => e.alive && e.type === 'sword_dummy').length === 0, onComplete: 'spawnArrowDummies' },
      { text: 'R TO AIM BOW, CLICK TARGET, R TO SHOOT', check: (s) => s.enemies.filter((e) => e.alive && e.type === 'arrow_dummy').length === 0 },
      { text: 'PRESS E NEAR MASTER REN', check: (s) => s.player.talkedToMaster, onComplete: 'spawnSlimes' },
      { text: 'FINAL TEST: DEFEAT ALL SLIMES', check: (s) => s.enemies.filter((e) => e.alive && e.type === 'slime').length === 0, onComplete: 'chooseElement' },
      { text: 'CHOOSE YOUR ELEMENT!', check: (s) => s.player.element !== null, onComplete: 'spawnElementTargets' },
      { text: 'PRESS X TO USE YOUR ELEMENT!', check: (s) => s.player.elementUsed },
      { text: 'TALK TO MASTER REN AGAIN (E)', check: (s) => s.player.graduationTalkDone, onComplete: 'graduation' }
    ],
    lastTick: 0,
    groundY: (h) => h * GROUND_RATIO
  };
}
